
title: Thomas Mar Wee
email: thomasmarwee@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Thomas Mar Wee is a writer, poet, and editor based in Brooklyn, New York.
baseurl: "" # the subpath of your site, e.g. /blog
url: "thomasmarwee.com" # the base hostname & protocol for your site, e.g. http://example.com
author: Thomas Mar Wee

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag


collections_dir: contentFolder

collections:
  - fiction
  - interviews
  - poetry
  - essay-criticism
  - about

